cors:
      origins:
        - https://johnsheffinet-legendary-eureka-wgpr6xg496c9764-4002.preview.app.github.dev
        - https://studio.apollographql.com # Allows Apollo Studio to still run queries against your Router
